server:
  port: 8011


spring:
  profiles:
    active: dev
  application:
    name: service-admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?characterEncoding=UTF-8
    username: root
    password: root



mybatis-plus:
  type-aliases-package: com.guli.admin.pojo
  mapper-locations: classpath:com/guli/admin/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
