server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB

aliyun:
  oss:
    file:
      endpoint:
      keyid:
      keysecret:
      bucketname:
